- src/app/element.js
- src/display/canvasrenderer.js
Layer系で自分が持ってるrendererで描画してsceneのrendererで描画したくないときなどに使うと思います。
よかったらマージお願いします
> CanvasRenderer でchildrenを描画するかフラグを追加しました

- src/asset/assetloader.js
- src/asset/font.js
- src/config.json
アセットローダでのフォント読み込みに対応しました。
keyが必要となる為、assetLoadFunctionsの引数を変更しています。
> アセット読み込みのフォント対応

- src/geom/vector2.js
> Vector2 fix

- src/config.json
- src/input/gamepad.js
- test/game/src/input/index.js
> add gamepad

- src/asset/font.js
@daishihmr san, @minimo san
確認よろしく♪
> webfont のロードチェック時にタイムアウト判定するよう修正

- src/app/baseapp.js
> add accessor baseapp.

- src/display/sprite.js
- test/game/src/display/index.js
SpriteにframeIndexを追加しました。
それに伴い、初期化時にサイズを指定する仕様に変更しております。
ご確認よろしくお願いします！
> SpriteにframeIndexを追加

- src/display/canvasapp.js
> add fit flag canvasapp

- src/ui/button.js
ボタンのテキストなどを直接変えられるaccessorを追加しました。
（もっと良いプロパティ名があれば修正お願いします）
* text → テキスト
* textSize → フォントサイズ
* textColor → テキストの色
* bgColor → ボタンの色
以下は、fix です。
* ダブっているonpointendやsetInteractiveを削除
* FlatButtonの親クラスをBaseButtonに修正
> fix and add accessor

- examples/touchgame.html
- src/display/label.js
- src/display/shape.js
- src/effect/wave.js
- src/game/countscene.js
- src/game/resultscene.js
- src/game/titlescene.js
- src/ui/button.js
- test/game/src/display/index.js
結構大規模な改修
- shape の style の仕組みを廃止
- color -> fill
- stroke -> bool 値だったのを色に変更
- Label の引数を１個に制限
> refactor shape

- src/game/loadingscene.js
> LoadingScene修正

- src/ui/button.js
- test/game/src/ui.js
> change button to sharp base

- src/util/tween.js
tm.anim.easing -> phina.util.Tween.EASING
> phina.util.Tween.EASINGがtmを参照している箇所があったので修正

- src/game/resultscene.js
細かくてすみませんが
* phina → phina_js
* stroke: false → null
> ResultSceneのデフォルトのハッシュタグをfix

- src/input/keyboard.js
> fix Keyboard

- src/display/canvaselement.js
- src/display/canvaslayer.js
- src/display/canvasrenderer.js
> rename childrenVisible -> renderChildBySelf

- src/input/touch.js
touch のgetPointingが常にtrueになるのを直しました
> bugfix touch

- src/display/sprite.js
- test/game/src/display.js
raduisプロパティの影響でスプライトの大きさが変わっていたので、drawメソッドを修正しました。
> fix and add test

- src/asset/sound.js
- test/game/src/asset.js
Soundクラスに以下のアクセサを追加しました。
* loop
* loopStart
* loopEnd
> set  loopStart and loopEnd

- src/graphics/canvasrecorder.js
> fix canvasrecorder

- src/input/touch.js
> bugfix touchlist

- examples/breakout.html
他のexamplesの名残などがあったので、その個所を削除しました。
> examplesのbreakoutのfix

- src/game/managerscene.js
tmを参照してるコードが残ってたようです。
よろしくお願いします。
> ManagerScene終了時にエラー

- src/game/gameapp.js
https://github.com/phi-jp/phina.js/issues/61
　の件です。
必要であればmergeお願いします
> fix issue#61 phina.game.GameApp crashes with no globalize

- src/display/canvasapp.js
> modify default parameter to static

- src/game/managerscene.js
globalize() 使ってないときでも動くようにしました!
namespace を省略したシーンがあればそっちを使い,
なければ phina.game 内のを使うようにしてます!!
@altkaye san, @daishihmr san
よかったらレビューお願いします!!
> support time when don't use globalize()

- src/game/pietimer.js
color -> fill
strokeStyle -> stroke
this.style -> this
> PieTimerが旧仕様になっていたので修正

- src/accessory/physical.js
> Add method named addForce

- src/core/object.js
- src/display/label.js
- src/display/shape.js
- src/game/pietimer.js
- src/phina.js
- src/ui/button.js
- src/ui/gauge.js
- test/game/src/display.js
- test/game/src/ui.js
- _renderBackground 廃止
- render を draw でやるよう修正
- $watch を導入
- わざわざ accessor 定義していたのを $watch 使う形に置き換え
> Shape 系の実装を見直し

- src/display/shape.js
- lineWidthに0以下を設定しても無視されるので、元々の線幅が適用されてしまう
> strokeWidthが0以下の時は線を描画しない

- src/display/canvasapp.js
- src/display/domapp.js
GameAppでfpsとbackgroundColorもオブジェクトで渡せた方が便利だと思ってpullreqしましたー
> GameAppなどでオプションからfps,backgroundColorを指定できるように

- src/display/shape.js
> watchRenderProperties が callで使用できない問題を修正

- src/asset/texture.js
> スプライト用のテクスチャを透明色指定で透過処理可能にする

- src/geom/vector2.js
#69 を実装してみました
それぞれの方向の大体+-45°の範囲で判定します
```javascript
switch(true)
```
使ってますが、問題ありそうでしたらif-elseで書き直します…
> vector2.getDirectionを実装 refs #69

- src/asset/assetloader.js
- src/asset/file.js
#66 を実装してみました
json/xml/html/textはいけました
> assetLoadFunctionsにjson/xml/textを実装 refs #66

- examples/breakout.html
- src/config.json
- src/game/gameapp.js
- src/game/managerscene.js
- src/game/pausescene.js
- test/game/src/game.js
- test/game/templates/display.html
- GameApp に enableDebugger() を追加
- PauseScene を追加
> debug 機能を強化

- src/accessory/physical.js
> Physicalクラスのメソッドをチェイン可能に

- src/display/label.js
- src/display/shape.js
- src/game/pietimer.js
- src/ui/button.js
- src/ui/gauge.js
- src/ui/labelarea.js
calcCanvasSizeを実装
prerender内に
canvas.clearColor()
canvas.transform()
を含めるように修正
テストOK
> shape calcCanvasSize prerenderの修正

- src/accessory/tweener.js
_updateTaskで、_loopフラグが立っていても正しく動作する方向に修正するかで迷ったのですが、
clearで_loopフラグを戻せば解決するので、こんな感じにしてみました。
あと、stopの方は、rewindの中でplayを呼んでいたのが原因だったので
呼び出し順を変更して解決しました。
ソースコードを使わないと伝えにくかったので、issueを立てる代わりにpullreqしました。
> bugfix tweener

- src/display/shape.js
> fix pathshape

- src/asset/texture.js
tmlib.js で、Bitmap にあったような
フィルターメソッドがほしいです。
作ってみましたがどうでしょうか？
> add texture filter method

- src/asset/sound.js
if(this.source)が意味ないと思ったので消しました
> fix sound stop

- src/geom/vector2.js
仕切り直しです。
* 法線（垂直）ベクトルを求めるメソッドの追加
* reflect メソッド内の脱字修正
よろしくお願いします♪
> 垂直ベクトル追加 & reflectの脱字修正

- src/ui/labelarea.js
読みやすくなるように頑張りました!
自分ではこれが限界です！
> LabelAreaのgetLinesの可読性を高めたと思う

- src/core/array.js
- test/common/src/core/array.js
array most実装しました。とテストも書きました。
```
[1,2,111].most() //{max:111, min:1}
[{x:100,y:-100},{x:1,y:0}].most(o=>o.x)//{max:{x:100,y:-100},min:{x:1,y:0}}
```
> array most 実装

- src/geom/collision.js
@phi-jp さん プルレクさせて頂きます。
問題なければマージよろしくお願いします♪
> Collisionクラスに円と2点を結ぶ線分の当たり判定を行うメソッドの追加

- src/core/array.js
最初のドキュメント追加版です。文体、構成、内容など要望ありましたらコメントください。
ここである程度の標準スタイルを決めて、他のクラスのドキュメントを用意していきたいと思います。
> global.Array のドキュメント

- src/core/array.js
- src/core/date.js
- src/core/math.js
- src/core/number.js
- src/core/string.js
object.js については、普通の phina.js ユーザーはあまり詳しく知る必要はなさそうなので優先度低にしています。
どちみちこれを使いたい人はソース見て理解できる人でしょうし(笑)。
> core系クラス（date.js, math.js, number.js, string.js）のドキュメントを追加

- src/app/element.js
- test/game/src/app.js
defaultsのkeys
_hierarchiesのクラスのdefaultsのkeys
className
name
children
child.name or className + '_' + i
でtoJSONされたものをchildrenに突っ込んでいく
以上のプロパティをjsonにします
> toJSON を改修

- src/ui/labelarea.js
- test/game/src/ui.js
> 行の最後の文字でちょうど改行される場合に改行されないバグ修正

- src/core/string.js
- src/ui/labelarea.js
- test/common/src/core/string.js
- test/game/src/ui.js
@simiraaaa san
だいぶ変えちゃいました.
見通しはよくなったと思います.
あと JIT が効きやすいコードにしたのでおそらく若干以前のコードより速くなると思います!
> refactor LabelArea class

- src/asset/texture.js
もしかしたら下記でimageのasset読み込みが失敗する可能性があるかも
img 要素の src 属性と onload イベントリスナの設定タイミング
http://please-sleep.cou929.nu/onload-handler-setting-timing-and-async-request-of-image-element.html
> imgのsrcのハンドラ設定タイミングを変更

- src/util/eventdispatcher.js
> 一度リスナーを登録して削除した後hasがtrueを返してしまうバグを修正しました

- src/asset/sound.js
Sound.volume をいじるとマスターボリュームが変更できるようにしました。
> マスターボリューム実装

- src/asset/sound.js
> Sound の onended を when, offset, durationを考慮したものに修正しました。

- src/display/displayelement.js
alpha < 0　の場合、透過設定が無効になることへの対策
> alpha < 0の時は、描画前にalpha = 0に補正する

- src/accessory/frameanimation.js
よろしくお願いします。
動作確認サンプル
http://runstant.com/alkn203/projects/13ddc7d1
> フレームアニメーションのキープ

- src/ui/gauge.js
はじめまして。
些細な変更で恐縮ですが、[issue#208](https://github.com/phinajs/phina.js/issues/208)にて指摘されてましたmaxValue関連のバグを修正しました。
よろしくお願いいたします。
> fix ui.Gauge maxValue bug

- src/input/mouse.js
- マウスのフラグ判定の修正
- マウスがcanvas要素の外に出たときにその時の座標で左クリックをmouseupしたことにする対応
> fix mouseout of canvas

- src/ui/gauge.js
#227 のプルリクです。
併せて、プロパティを defaults 形式にしました。
以下、サンプルです。
http://runstant.com/alkn203/projects/adeaa5c3
> Set gauge default value to max

- src/social/twitter.js
- コンストラクタはいらないと思ったので消した
- 使われていない変数`BASE_URL`を消した
- `baseURL`をhttpsにした
> edit phina.social.twitter

- src/accessory/frameanimation.js
> 【Fix】同じフレームアニメーションの場合巻き戻さないようにする
