phinajs/phina.js

- src/display/canvasapp.js
CanvasAppのbackgroundColorプロパティに値が入っていない場合、Canvasをクリアするように修正しました。
> CanvasAppの背景色を透明に設定可能に

- src/phina.js
phina.defineでのクラス定義時、superClassに指定したクラスが未定義だった場合は、親クラスが定義されるまで子クラスの定義実行を待つように修正しました。
実装はtm.define()を参考にしています。
> phina.define()で未定義のクラスを継承したクラスを定義可能に

- src/asset/assetloader.js
AssetLoaderでSoundロード時の変数名に間違いがありましたので修正しました。
> AssetLoader変数名違い修正

- src/accessory/frameanimation.js
FrameAnimationでnextが指定されてない場合、アニメーション終了後に再生を止める様にしました。
pausedフラグをfalseにすると再度最初から再生されます。
確認よろしくお願いします。
> FrameAnimationで再生終了時nextが指定されてない場合の挙動追加

- src/display/shape.js
fill == null の場合、塗りつぶしをしないようにしました。
transparent指定せずに、枠だけのShapeを作ることができます。
> RectangleShape と CircleShapeに塗りつぶし判定追加

- src/display/shape.js
Shapeが表示されなかったので、変数宣言の順番を変更しました。
var w = image.width;
var h = image.height;
を先に宣言
> shape.js draw内の変数宣言の順番を変更

- src/display/shape.js
CircleShapeのradiusを変えても_widthと_heightがデフォルトのサイズのままなので、_radius*2として、left、right、top、bottomが正しく機能するようにしました。
> CircleShapeのradiusプロパティ設定時にwidthとheightも併せて設定

- src/util/grid.js
コンストラクタで位置のオフセット値を与えると、実際のオブジェクトの配置の時は、その辺りを意識せずにコードが書けて便利かと思います。
> Gridクラスのコンストラクタでオフセット値を指定可能に

- src/input/touch.js
大幅にかわりましたが、動作自体に影響はありません。今までどおりの動きになります。
AndroidでTouchEvent のidentifierが重複してしまい処理効率が悪くなるので、IDを自分で割り当てるようにしてあります。
filterなしでtouchMap[id]から直接Touchクラスを参照するので速くなりました。
iPhoneで6本以上タッチしたときOS側でtouchがキャンセルされるので、ずっとtouchしたままの状態になっていたのを修正しました。
> touchlist 改修

- src/util/eventdispatcher.js
clearなどのメソッドは継承先で使われる可能性が高いので、古い名前(addEventListener)など別名でも定義しました。
> EventDispathcerの別名メソッド

- src/asset/asset.js
- src/asset/assetloader.js
- src/asset/sound.js
- src/game/loadingscene.js
Asset クラスに loadDummy (ローカルだけで完結できるものをセットするための抽象メソッド)
Soundクラスの_loadでロード失敗時に失敗したフラグをセットし成功したことにするように変更。
LoadingSceneでゲージがいっぱいになったときロードに失敗しているアセットはダミーをセット
```javascript
assets:{
sound:{
dummy:'dummy.mp3',
test:'test.mp3',
}
}
```
みたいに アセットのキーを`'dummy'`にしたものがdummy読み込み用のアセットになります。
dummyがない場合は、loadDummyします。
> asset のロード失敗時の対策

- src/asset/sound.js
assetで読み込めない形式の際のエラーがうまく表示できていなかったので修正しました
chromiumなどでmp3などを読み込むと再現できると思います
ここは治せたんですが、このあと読み込めなかったファイルを再生したりすると
エラーが起こるのでどうしても読み込めなかった場合は実行不可能になりますね…
その先で存在確認してどうこうすればいけなくもないですが
> assetで読み込めない形式のエラーの修正

- test/common/src/geom/index.js
- 360度を引いた結果が負の数の場合に、判定が正しく行われない
> テストが正しくなかったのを修正

- src/accessory/tweener.js
issue　#52 
対応
_getUnitTime(app) タイプに合わせた時間を取得　想定外のタイプの場合は1000/app.fps
_static: getUnitTimeMap{} タイプに合わせた時間を取得するための関数が入ったオブジェクト
setType(type) メソッドチェーン
FPSのTweenerが早く欲しかったのでとりあえず実装してみました。
> Tweener　クラスにタイプの変更を追加 (更新方法をFPSでするかなど）

- src/phina.js
> superMethod の引数がメソッド名を含めたものが渡されているバグ修正

- src/accessory/frameanimation.js
target.width=frame.width
target.height=frame.height
をなくしました
> FrameAnimationを使うとSpriteのサイズ変更ができないものを修正

- src/accessory/frameanimation.js
- src/app/scene.js
後方互換が軒並み死ぬので一旦 fit フラグを持たせてデフォルト true にしました.
下記のようにすれば勝手に fit しなくなります.
```
fa.fit = false;
elm.width = 128;
elm.height = 128;
```
> フレームアニメーションのサイズを反映させるかどうかをフラグで分岐

- src/ui/labelarea.js
よく考えたら、ダミーを作る必要がなかったので修正しました。
tmlibのときはLabelがコンテキスト持ってなかったので、そういう仕様でした。
> LabelArea context 修正

- src/asset/assetloader.js
- test/game/src/asset.js
progressが count/flows.length になってるが、直接書いてあるspritesheetの場合flow.thenが即時発生するためprogressが1になることがあり、その結果、LoadingSceneで読み込みか完了する前に次のシーンへ遷移してしますという現象を修正しました。
> AssetLoader の spritesheet をソースに直接書いて読み込む場合に発生するバグを修正しました

- src/accessory/tweener.js
- src/display/canvasapp.js
- src/display/domapp.js
- src/phina.js
- src/util/ticker.js
- UAの判定の強化、拡張
- Tickerのループに使う関数を任意でセットする機能の実装(ticker.runner)
- TweenerのupdateTypeのデフォルトを `'normal'` から `'delta'`に変更
Androidのみrunnerを指定しない場合はrequestAnimationFrameになるようにしました。
タッチで一瞬止まる問題は解消しました。
任意でセットすることも可能
```js
DomApp({runner:requestAnimationFrame})
CanvasApp({runner:requestAnimationFrame})
GameApp({runner:requestAnimationFrame})
```
self.runner()で呼び出していないのは https://github.com/phi-jp/phina.js/commit/1258769fdf08087ad41f5ff0def0076c4fbe375e
Illegal invocation 対策のため
これはthisとなるオブジェクトが想定外の場合に出るエラー
> requestAnimationFrame 対応

- src/app/interactive.js
他、pointend即pointoutとなる挙動がPCでは発生せず、モバイル環境でのみ有効になるよう変更しました。
> ボタンを1度クリックするとポインタの形状が固定されてしまうバグの修正

- src/input/input.js
- test/game/src/input.js
canvasの位置とサイズによってポインタの座標を正確に計算するようにしました。
cssのwidthやheight, transformのscale, translate等でcanvasの位置を自由に動かしてもクリックの判定がずれないようになりました。
`/test/game/#input.Input/adjust_scale` にテストを追加しました。
> ポインタの座標の計算方法を修正

- src/app/baseapp.js
- src/util/ticker.js
- test/game/src/app.js
BaseAppにkillメソッドを実装しました。
appをkillした場合、appの参照がなくなれば、完全にメモリから解放されることを想定しています。
- kill() を実行した時 ticker の tick イベントリスナから削除されていることを確認
- ticker の stop() を実行した次のフレームから ticker の runner が呼ばれないことを確認
- kill() 後に run() で再起動できることを確認
> BaseApp killメソッド実装

- src/app/baseapp.js
描画後にinteractiveのcheckをしていたのを描画前にするようにしました。
以下、改善される項目です
- pointer系のイベントでの処理が1フレーム遅れずに反映される
> BaseAppの_loop内でinteractive.checkのタイミングを変更
